name: dock_router
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:

  plugin:
    platforms:
      android:
        package: com.example.dock_router
        pluginClass: DockRouterPlugin
      ios:
        pluginClass: DockRouterPlugin
